### ISSUE TITLE
Interaction not working

### ISSUE THREAD

**Issue by oniseijin** [sagemath/cloud#154]
The below works in Sagemath 6.1.1, but gives an error regarding an unexpected variable when run in SageCloud as a sage work space. Images below

Project ID: 157ab505-0883-47a9-a680-ece47dee0d82

```
p=0.004 # odds of the event happening
n=150 # number of times this is run


def f(p, n):
    '''
    This determines the chances of an event happening at least once

    First, you do the chance of it not happening, n number of times (1-p)
    Then you have (1 - answer) to see the odds of it happening (at least once)
    '''
    r = (1-p)^n
    return 1 - r

@interact
def probability(p=input_box(p, type = float), n=slider(vmin=1, vmax=1000, default=n, step_size=1)):
    """
    """

    show(f(p,n))

    x_coords = [1..1000]
    y_coords = [f(p, x) for x in x_coords]


    y = list_plot(zip(x_coords, y_coords), plotjoined=True)

    show(y)
︡1428ce8c-4384-4178-80f6-d4aed29873e2︡{"stderr":"Error in lines 7-14\nTraceback (most recent call last):\n  File \"/projects/157ab505-0883-47a9-a680-ece47dee0d82/.sagemathcloud/sage_server.py\", line 736, in execute\n    exec compile(block+'\\n', '', 'single') in namespace, locals\n  File \"\", line 2, in <module>\nTypeError: slider() got an unexpected keyword argument 'vmin'\n"}︡
```

NOT WORKING IN CLOUD: 
![not-working](https://cloud.githubusercontent.com/assets/80143/3711598/674146be-14df-11e4-8760-66cdf7954d21.png)
WORKING ON 6.1.1
![working](https://cloud.githubusercontent.com/assets/80143/3711599/6ae02b28-14df-11e4-89de-e6317f16917e.png)
